<?php

/**
 * @file
 * Contains install and update functions for View Mode Selector.
 */

/**
 * Implements hook_field_schema().
 */
function view_mode_selector_field_schema($field) {
  return array(
    'columns' => array(
      'value' => array(
        'description' => 'Machine-readable name of view mode.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
      ),
    ),
  );
}
